Repository gitsobek/ngx-infi-markdown, pull requests merged in 2020-07, with the labels that each got.

#1 chore(commitlint): lint commit on conventional commits
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#2 feat(editor): provide proper enter/backspace/delete handling for editor, enable initial entity loading from persistence
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.scss
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.ts
  projects/ngx-infi-markdown/src/lib/_core/models/Payload.ts
  projects/ngx-infi-markdown/src/lib/_core/services/tree.service.ts
  projects/ngx-infi-markdown/src/lib/_core/utils/index.ts
Labels: enhancement

#4 chore(editor): arrow/enter/backspace/delete handling for nested rows
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.ts
  projects/ngx-infi-markdown/src/lib/_core/services/tree.service.ts
  projects/ngx-infi-markdown/src/lib/_core/utils/index.ts
Labels: enhancement

#6 feat(editor): add ordered and unordered list
  projects/ngx-infi-markdown-showcase/src/app/app.component.ts
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.scss
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.ts
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.scss
  projects/ngx-infi-markdown/src/lib/_core/models/Tag.ts
  projects/ngx-infi-markdown/src/lib/_core/services/tree.service.ts
  projects/ngx-infi-markdown/src/lib/_core/utils/index.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.component.ts
Labels: enhancement

#7 fix(toolbar): fix tags placement when dragging or resizing, fix styling
  projects/ngx-infi-markdown-showcase/src/app/app.component.scss
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.scss
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.ts
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.scss
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.ts
  projects/ngx-infi-markdown/src/lib/_core/components/preview/preview.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/preview/preview.component.scss
  projects/ngx-infi-markdown/src/lib/_core/directives/resizable.directive.ts
  projects/ngx-infi-markdown/src/lib/_core/services/tree.service.ts
Labels: fix

#8 feat(editor): add tooltip & display above tags on hover
  angular.json
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/tooltip/tooltip.component.scss
  projects/ngx-infi-markdown/src/lib/_core/components/tooltip/tooltip.component.ts
  projects/ngx-infi-markdown/src/lib/_core/directives/tooltip.directive.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.module.ts
Labels: enhancement, fix

#9 refactor: update models, replace deprecated Injector, unsubscribe obs…
  projects/ngx-infi-markdown-showcase/src/app/app.component.ts
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.ts
  projects/ngx-infi-markdown/src/lib/_core/directives/tooltip.directive.ts
  projects/ngx-infi-markdown/src/lib/_core/models/Style.ts
  projects/ngx-infi-markdown/src/lib/_core/pipes/sanitizeHtml.pipe.ts
  projects/ngx-infi-markdown/src/lib/_core/services/tree.service.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.component.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.service.ts
Labels: enhancement, fix

#10 feat(ctx): add one time configuration in root module
  projects/ngx-infi-markdown-showcase/src/app/app.module.ts
  projects/ngx-infi-markdown/src/lib/_core/configs/index.ts
  projects/ngx-infi-markdown/src/lib/_core/services/tree.service.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.component.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.module.ts
Labels: enhancement

#11 feat(app): add persistent storage & prepare for release
  .all-contributorsrc
  README.md
  package-lock.json
  package.json
  projects/ngx-infi-markdown-showcase/src/app/app.component.html
  projects/ngx-infi-markdown-showcase/src/app/app.component.scss
  projects/ngx-infi-markdown-showcase/src/app/app.module.ts
  projects/ngx-infi-markdown-showcase/src/assets/ordered-list.png
  projects/ngx-infi-markdown-showcase/src/assets/unordered-list.png
  projects/ngx-infi-markdown-showcase/src/index.html
  projects/ngx-infi-markdown/src/assets/align-center.png
  projects/ngx-infi-markdown/src/assets/align-left.png
  projects/ngx-infi-markdown/src/assets/align-right.png
  projects/ngx-infi-markdown/src/assets/ordered-list.png
  projects/ngx-infi-markdown/src/assets/unordered-list.png
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.scss
  projects/ngx-infi-markdown/src/lib/_core/components/editor/editor.component.ts
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.scss
  projects/ngx-infi-markdown/src/lib/_core/configs/index.ts
  projects/ngx-infi-markdown/src/lib/_core/services/storage.service.ts
  projects/ngx-infi-markdown/src/lib/_core/services/tree.service.ts
  projects/ngx-infi-markdown/src/lib/_core/utils/index.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.component.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.module.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.service.ts
Labels: enhancement, fix

#12 release: v1.0.0
  README.md
  package.json
  projects/ngx-infi-markdown/README.md
  projects/ngx-infi-markdown/package.json
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.html
  projects/ngx-infi-markdown/src/lib/_core/components/min-toolbar/min-toolbar.component.ts
  projects/ngx-infi-markdown/src/lib/_core/services/storage.service.ts
  projects/ngx-infi-markdown/src/lib/ngx-infi-markdown.component.scss
Labels: documentation, enhancement, fix
